# IFPB - CAMPUS CAMPINA GRANDE

# ALUNO: ARYELSON GONÇALVES MESSIAS  TURMA: A

## Lista de Exercícios 2a

#### 1.Como importar a biblioteca numpy e verificar a versão utilizada?

Primeiramente vamos importar a biblioteca.

In [1]:
import numpy as np

Agora vamos verificar a versão.

In [2]:
print (np.__version__)

1.20.1


#### 2.Explique, com suas palavras, os conceitos de vetorização e broadcasting que Numpy implementa.


    O termo broadcasting é usado para informar como a biblioteca numpy trata array diferentes maneiras durante operações artiméticas. Vetorização permite usar uma função em um array completo, no lugar de aplicar a função em um elemento por vez, o que é feito nas funções map e filter.

#### 3. Liste as diferenças entre uma lista, um dicionário, um array numpy, dando exemplos de aplicação de em que cada tipo seria mais interessante.

    lista é um array que varia de tamanho e é mutavel de acordo com índices. O dicionário tem por diferença principal e visível que o índice pode não ser um número e pode não ser sequencial, utilizando uma key para indetificar os elementos. A chave utilizada é do tipo caractere(String). Já um array em NumPy é uma tabela multidimensional de elementos do mesmo tipo, indexados por uma tupla de inteiros positivos.

Lista: Usada quando necessitamos de uma coleção ordenada de itens.

In [3]:
Lista = [1,4,6,5,8,7]
Lista.sort()
Lista

[1, 4, 5, 6, 7, 8]

Dicionário: Usado quando tiver um conjunto de chaves exclusivas que mapeiam para valores.

In [4]:
Dicionario = {"Nome": "Zé", "Cidade": "Nazarezinho", "Idade": 10,"CPF": "000.000.000-00"}
Dicionario

{'Nome': 'Zé', 'Cidade': 'Nazarezinho', 'Idade': 10, 'CPF': '000.000.000-00'}

Array Numpy: Usado quando tiver uma tabela multidimensional de elementos do mesmo tipo

In [5]:
arr = np.array([-2, '4', 7, 9])
arr

array(['-2', '4', '7', '9'], dtype='<U11')

#### 4. Forme a matriz

Matriz Formada com listas:

In [6]:
matriz = []
a = 1
for i in range(3):
    linha = []
    for j in range(1,6):
        linha.append(a)
        a += 1
    matriz.append(linha)
matriz2 = []

for i in range(5):
    linha = []
    for j in range(3):
        linha.append(matriz[j][i])
    matriz2.append(linha)
    
for i in matriz2:
    print(i)

[1, 6, 11]
[2, 7, 12]
[3, 8, 13]
[4, 9, 14]
[5, 10, 15]


Matriz formada usando os array do Numpy:

In [7]:
a = np.arange(1,16).reshape(3,5)
a = a.transpose()
a

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

#### 5. Usando numpy, crie:

(a) um vetor de 10 elementos entre 1 e 20

In [8]:
a = np.random.randint(1, 21, size=10)
a

array([19, 13, 16,  1, 13, 15,  3, 18,  1, 14])

(b) um vetor entre 1 e 20, com passo de 2

In [9]:
a = np.arange(1, 21, 2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

(c) uma matriz 3x3 cujos elementos da diagonal sejam o vetor [1,2,3] e os demais
sejam todos 0

In [10]:
a = np.zeros((3,3))
a = np.diag(np.arange(1,4))
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])