In [1]:
import pandas as pd
import numpy as np

In [2]:
# Função disponibilizada pelo professor Paulo Ribeiro, com algumas alterações no codigo.
def dist_frequencia_classes(x, nc='auto'):
    #função histogram do numpy para calcular as freq. absolutas e intervalos das classes
    fa,classes= np.histogram(x, bins=nc) 
    fa = fa.astype(int)#pra transformar em int 
    #freq. relativas = freq. absolutas/no. de dados do conjunto x 100 pra forma percentual
    fr = np.around(fa/fa.sum()*100,decimals=2) #duas casas decimais
    #freq. cumulativa usando a função cumsum do numpy
    #frnorm = np.around(fi/(fi.sum() * np.diff(classes)),decimals=2)
    fc = np.cumsum(fa).astype(int) #pra transformar em int 
    # o laço a seguir serve unicamente para escrever os intervalos das classes como strings
    # dentro do vetor 'classe_str'
    classe_str = []
    for i in range(len(classes)):
        if i<=len(classes)-2:
            classe_str.append('{:2.0f} |--  {:2.0f}' .format(classes[i] if i==0 else classes[i]+1,classes[i+1]) )
        else:
            break        
    # a função retorna um dataframe, cujas linhas serão indexadas pelo vetor 'classe_str', e as 
    #colunas terão as frequências absoluta (inteira), relativa (float) e cumulativa (int) calculadas 
    return pd.DataFrame({'Classes':classe_str, 
                         'fi': fa,
                         'fr': fr,
                         #'frnorm':frnorm,
                         'Fc': fc
                        }).set_index('Classes') # transforma a coluna 'Classes' nos indices das linhas 


In [3]:
df = pd.DataFrame({'Nome': ['Joao da silva ', 'Pedro fernandes' , 'Maria freitas','Paula gonçalves','ana freitas','luiz costa','andre souza','patricia silva', 'regina lima','alfredo souza','margarete cunha','pedro barbosa','ricardo alves','marcio rezende','ana carolina chaves'],
                   'Idade': [36,51,26,25,29,53,42,38,35,45,26,37,24,31,29],
                 'Salario': [6300,5700,4500,3800,3200,7300,7100,5600,6400,7000,3700,6500,4000,5100,4500]})

# Atividade 2.1

1. Calcular a amplitude do conjunto de dados

$A = x_{max} - x_{min}$

2. Calcular o número de classes (intervalos)

$N_c = \sqrt n$: raiz quadrada

$N_c = 1+ 3.3log(n)$: Sturges

3. Tamanho das classes

$h = \dfrac{A}{N_c}$


#### Representação do intervalo

$a \vdash b \Rightarrow [a,b)$

In [4]:
A = df['Idade'].max() - df['Idade'].min()
A

29

In [5]:
Nc = np.sqrt(len(df))
Nc

3.872983346207417

In [6]:
h = A/Nc
h

7.487767802667673

##### Calculando frequencias relativa e cumulativa

In [7]:
dados = df['Idade'].dropna()
fi, classes = np.histogram(dados,bins=5)
fi

array([6, 2, 3, 2, 2], dtype=int64)

In [8]:
fr = fi/fi.sum()
fr

array([0.4       , 0.13333333, 0.2       , 0.13333333, 0.13333333])

In [9]:
fr.sum()

1.0

In [10]:
frn, classes = np.histogram(dados,bins=5, density=True)
frn

array([0.06896552, 0.02298851, 0.03448276, 0.02298851, 0.02298851])

In [11]:
fr = frn*np.diff(classes)
fr

array([0.4       , 0.13333333, 0.2       , 0.13333333, 0.13333333])

In [12]:
Fc = fi.cumsum()
Fc

array([ 6,  8, 11, 13, 15], dtype=int64)

###### Utilizando a função Disponibilizada pelo professor Paulo Ribeiro

In [13]:
dist_frequencia_classes(dados, nc=7)

fi     fr  Fc
Classes                  
24 |--  28   4  26.67   4
29 |--  32   3  20.00   7
33 |--  36   2  13.33   9
37 |--  41   2  13.33  11
42 |--  45   1   6.67  12
46 |--  49   1   6.67  13
50 |--  53   2  13.33  15

# Atividade 2.2

1. Calcular a amplitude do conjunto de dados

$A = x_{max} - x_{min}$

2. Calcular o número de classes (intervalos)

$N_c = \sqrt n$: raiz quadrada

$N_c = 1+ 3.3log(n)$: Sturges

3. Tamanho das classes

$h = \dfrac{A}{N_c}$


#### Representação do intervalo

$a \vdash b \Rightarrow [a,b)$

In [14]:
A = df['Salario'].max() - df['Salario'].min()
A

4100

In [15]:
Nc = np.sqrt(len(df))
Nc

3.872983346207417

In [16]:
h = A/Nc
h

1058.6154479633606

##### Calculando frequencias relativa e cumulativa

In [17]:
dados = df['Salario'].dropna()
fi, classes = np.histogram(dados,bins=5)
fi

array([4, 2, 2, 3, 4], dtype=int64)

In [18]:
fr = fi/fi.sum()
fr

array([0.26666667, 0.13333333, 0.13333333, 0.2       , 0.26666667])

In [19]:
fr.sum()

1.0

In [20]:
frn, classes = np.histogram(dados,bins=5, density=True)
frn

array([0.0003252, 0.0001626, 0.0001626, 0.0002439, 0.0003252])

In [21]:
fr = frn*np.diff(classes)
fr

array([0.26666667, 0.13333333, 0.13333333, 0.2       , 0.26666667])

In [22]:
Fc = fi.cumsum()
Fc

array([ 4,  6,  8, 11, 15], dtype=int64)

###### Utilizando a função Disponibilizada pelo professor Paulo Ribeiro

In [23]:
dados = df['Salario'].dropna()
dist_frequencia_classes(dados, nc=5)

fi     fr  Fc
Classes                      
3200 |--  4020   4  26.67   4
4021 |--  4840   2  13.33   6
4841 |--  5660   2  13.33   8
5661 |--  6480   3  20.00  11
6481 |--  7300   4  26.67  15